/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SvgOptions {
  minWidth?: number
  minHeight?: number
  darkColor?: string
  lightColor?: string
}
export function qrcodeImage(text: string): Uint8ClampedArray
export function qrcodeSvg(text: string, options?: SvgOptions | undefined | null): string
export function qrcodeUnicode(text: string): string
