/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function qrcodeImage(text: string): Uint8ClampedArray
export function qrcodeUnicode(text: string): string
export function qrcodeSvg(text: string): string
