/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function qrcodeImage(text: string): Uint8ClampedArray
export function qrcodeUnicode(text: string): Uint8ClampedArray
export function qrcodeSvg(text: string): Uint8ClampedArray
export class QrCode {
  constructor(input: string)
  asyncImage(signal?: AbortSignal | undefined | null): Promise<Uint8ClampedArray>
  asyncSvg(signal?: AbortSignal | undefined | null): Promise<Uint8ClampedArray>
  asyncUnicode(signal?: AbortSignal | undefined | null): Promise<Uint8ClampedArray>
}
